### ISSUE TITLE
Donut Chart mengecil sampe ilang pas di hover

### ISSUE THREAD

**Issue by aubertlenno** [WADSFinalProject/Mori_frontend#35]
di monitoring centra xyz itu kan ada 3 donut chart, itu kalo di hover jd kecil trs ilang. Contohnya di video. @priscillabigaill 

https://github.com/WADSFinalProject/Mori_frontend/assets/88722555/d3d174d5-28ab-4038-b5b2-0592bbcd9e65

**Comment by aubertlenno** [comment]
Oh sama di monitoring centra juga, font weight drying machine sama flouring machine ketebelan deh kayanya, dibikin semibold aja.

sama tulisan monitoring centranya keknya kalo bold lebi bagus deh dibanding extra bold

**Comment by priscillabigaill** [comment]
okay, noted. @audreyfabiola

**Comment by audreyfabiola** [comment]
ok

**Comment by audreyfabiola** [comment]
> di monitoring centra xyz itu kan ada 3 donut chart, itu kalo di hover jd kecil trs ilang. Contohnya di video. @priscillabigaill
> 
>  Vite.+.React.-.Google.Chrome.2024-06-08.15-15-36.-.Trim.mp4

Ini kayaknya ngebug aja yaa, di laptop yang lain amann
